const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let admin=null,users=[],transactions=[],audit=[];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2600)}
function showLogin(){$('#login').classList.remove('hidden');$('#admin').classList.add('hidden')}
function showAdmin(){$('#login').classList.add('hidden');$('#admin').classList.remove('hidden')}
function setView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='dashboard')loadDashboard();if(v==='users')loadUsers();if(v==='transactions')loadTransactions();if(v==='audit')loadAudit()}
async function boot(){const {data}=await db.auth.getSession();if(data.session)await checkAdmin(data.session.user);db.auth.onAuthStateChange(async(_,s)=>{if(s)await checkAdmin(s.user);else{admin=null;showLogin()}})}
async function checkAdmin(u){const {data:p,error}=await db.from('profiles').select('id,full_name,role,active').eq('id',u.id).single();if(error||!p||p.role!=='admin'||!p.active){await db.auth.signOut();toast('This account is not authorized as an Asal Pay administrator.');return}admin=p;$('#adminName').textContent=p.full_name||u.email||'Administrator';showAdmin();await loadDashboard()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)toast(error.message)};
$('#logout').onclick=()=>db.auth.signOut();
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$$('[data-view]').filter(x=>!x.classList.contains('nav-item')).forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#refresh').onclick=loadDashboard;$('#userRefresh').onclick=loadUsers;$('#txRefresh').onclick=loadTransactions;
async function loadDashboard(){if(!admin)return;const [u,t,a]=await Promise.all([db.from('asal_profiles').select('id,full_name,phone,email,active,wallet_id,created_at,asal_wallets(balance,currency)').order('created_at',{ascending:false}),db.from('asal_transactions').select('*').order('created_at',{ascending:false}).limit(100),db.from('asal_admin_actions').select('*').order('created_at',{ascending:false}).limit(100)]);if(u.error||t.error||a.error){toast((u.error||t.error||a.error).message);return}users=u.data||[];transactions=t.data||[];audit=a.data||[];const total=users.reduce((s,x)=>s+Number(x.asal_wallets?.[0]?.balance||0),0);$('#statUsers').textContent=users.length;$('#statBalance').textContent=money(total);$('#statTx').textContent=transactions.length;$('#statActive').textContent=users.filter(x=>x.active!==false).length;renderMiniTx();renderMiniAudit()}
function renderMiniTx(){const map=new Map(users.map(u=>[u.id,u]));$('#recentTx').innerHTML=transactions.length?transactions.slice(0,6).map(t=>'<div class="mini-row"><div class="mini-main"><strong>'+esc(t.note||t.transaction_type||'Transaction')+'</strong><span>'+esc(map.get(t.sender_id)?.phone||'System')+' → '+esc(map.get(t.recipient_id)?.phone||'System')+' · '+new Date(t.created_at).toLocaleString()+'</span></div><div class="mini-amount">'+money(t.amount)+'</div></div>').join(''):'<div class="mini-row"><span>No transactions yet.</span></div>'}
function renderMiniAudit(){const map=new Map(users.map(u=>[u.id,u]));$('#recentAudit').innerHTML=audit.length?audit.slice(0,6).map(a=>'<div class="mini-row"><div class="mini-main"><strong>'+esc(a.action)+'</strong><span>'+esc(map.get(a.target_user_id)?.phone||a.target_user_id||'System')+' · '+new Date(a.created_at).toLocaleString()+'</span></div><div class="mini-amount">'+(a.amount?money(a.amount):'—')+'</div></div>').join(''):'<div class="mini-row"><span>No admin actions yet.</span></div>'}
async function loadUsers(){if(!admin)return;const {data,error}=await db.from('asal_profiles').select('id,full_name,phone,email,active,wallet_id,created_at,asal_wallets(balance,currency)').order('created_at',{ascending:false});if(error){toast(error.message);return}users=data||[];renderUsers()}
function renderUsers(){const q=$('#userSearch').value.trim().toLowerCase();const rows=users.filter(u=>[u.full_name,u.phone,u.email,u.wallet_id].some(v=>String(v||'').toLowerCase().includes(q)));$('#usersTable').innerHTML=rows.length?rows.map(u=>{const w=u.asal_wallets?.[0]||{balance:0};return '<tr><td><div class="user-cell"><strong>'+esc(u.full_name||'Unnamed')+'</strong><span>'+esc(u.email||'No email')+'</span></div></td><td>'+esc(u.phone||'Not set')+'</td><td>'+esc(u.wallet_id||'—')+'</td><td><strong>'+money(w.balance)+'</strong></td><td><span class="badge '+(u.active!==false?'active':'off')+'">'+(u.active!==false?'Active':'Suspended')+'</span></td><td><div class="actions"><button class="action" data-user="'+u.id+'">Manage</button><button class="action credit" data-credit="'+u.id+'">Add</button><button class="action debit" data-debit="'+u.id+'">Remove</button></div></td></tr>'}).join(''):'<tr><td colspan="6">No users found.</td></tr>';$$('[data-user]').forEach(b=>b.onclick=()=>openUser(b.dataset.user));$$('[data-credit]').forEach(b=>b.onclick=()=>adjust(b.dataset.credit,'credit'));$$('[data-debit]').forEach(b=>b.onclick=()=>adjust(b.dataset.debit,'debit'))}
$('#userSearch').oninput=renderUsers;
async function openUser(id){const u=users.find(x=>x.id===id);if(!u)return;const balance=Number(u.asal_wallets?.[0]?.balance||0);$('#modalBody').innerHTML='<h2>'+esc(u.full_name||'Unnamed')+'</h2><div class="modal-sub">'+esc(u.phone||'No phone')+'</div><div class="balance-big">'+money(balance)+'</div><div class="adjust-grid"><button class="action credit" id="mAdd">Add funds</button><button class="action debit" id="mRemove">Remove funds</button></div><div class="detail-list"><div><span>Email</span><b>'+esc(u.email||'—')+'</b></div><div><span>Wallet ID</span><b>'+esc(u.wallet_id||'—')+'</b></div><div><span>Status</span><b>'+(u.active!==false?'Active':'Suspended')+'</b></div><div><span>Created</span><b>'+new Date(u.created_at).toLocaleString()+'</b></div></div><div class="adjust-grid" style="margin-top:14px"><button class="action" id="mToggle">'+(u.active!==false?'Suspend account':'Activate account')+'</button><button class="action" id="mReset">Send password reset</button></div>';$('#userModal').classList.remove('hidden');$('#mAdd').onclick=()=>adjust(id,'credit');$('#mRemove').onclick=()=>adjust(id,'debit');$('#mToggle').onclick=()=>toggleStatus(u);$('#mReset').onclick=()=>resetPassword(u)}
$('#closeModal').onclick=()=>$('#userModal').classList.add('hidden');$('#userModal').onclick=e=>{if(e.target.id==='userModal')$('#userModal').classList.add('hidden')};
async function adjust(id,direction){const u=users.find(x=>x.id===id);if(!u)return;const amount=Number(prompt((direction==='credit'?'Add funds to ':'Remove funds from ')+(u.full_name||u.phone)+' — amount'));if(!Number.isFinite(amount)||amount<=0)return;const reason=prompt('Reason for this wallet adjustment:')||'Admin wallet adjustment';if(!confirm((direction==='credit'?'Credit ':'Debit ')+money(amount)+' '+(u.full_name||u.phone)+'?'))return;const {data,error}=await db.rpc('asal_admin_adjust_wallet',{p_user_id:id,p_amount:amount,p_direction:direction,p_reason:reason});if(error){toast(error.message);return}toast('Wallet updated. New balance: '+money(data?.new_balance));$('#userModal').classList.add('hidden');await loadUsers();await loadDashboard()}
async function toggleStatus(u){const next=u.active===false;if(!confirm((next?'Activate':'Suspend')+' '+(u.full_name||u.phone)+'?'))return;const {error}=await db.rpc('asal_admin_set_status',{p_user_id:u.id,p_active:next});if(error){toast(error.message);return}toast(next?'Account activated.':'Account suspended.');$('#userModal').classList.add('hidden');await loadUsers()}
async function resetPassword(u){if(!u.email)return toast('This account has no email address for password reset.');const {error}=await db.auth.resetPasswordForEmail(u.email,{redirectTo:location.origin+location.pathname});if(error)toast(error.message);else toast('Password reset email sent.')}
async function loadTransactions(){if(!users.length)await loadUsers();const {data,error}=await db.from('asal_transactions').select('*').order('created_at',{ascending:false}).limit(500);if(error){toast(error.message);return}transactions=data||[];renderTransactions()}
function renderTransactions(){const map=new Map(users.map(u=>[u.id,u]));const q=$('#txSearch').value.trim().toLowerCase();const rows=transactions.filter(t=>[t.id,t.note,t.transaction_type,map.get(t.sender_id)?.phone,map.get(t.recipient_id)?.phone].some(v=>String(v||'').toLowerCase().includes(q)));$('#txTable').innerHTML=rows.length?rows.map(t=>'<tr><td>'+new Date(t.created_at).toLocaleString()+'</td><td>'+esc(t.transaction_type)+'</td><td>'+esc(map.get(t.sender_id)?.phone||'System')+'</td><td>'+esc(map.get(t.recipient_id)?.phone||'System')+'</td><td><strong>'+money(t.amount)+'</strong></td><td>'+esc(t.status)+'</td><td>'+esc(t.id.slice(0,8))+'…</td></tr>').join(''):'<tr><td colspan="7">No transactions found.</td></tr>'}
$('#txSearch').oninput=renderTransactions;
async function loadAudit(){if(!users.length)await loadUsers();const {data,error}=await db.from('asal_admin_actions').select('*').order('created_at',{ascending:false}).limit(500);if(error){toast(error.message);return}audit=data||[];const map=new Map(users.map(u=>[u.id,u]));$('#auditTable').innerHTML=audit.length?audit.map(a=>'<tr><td>'+new Date(a.created_at).toLocaleString()+'</td><td>'+esc(a.action)+'</td><td>'+esc(map.get(a.target_user_id)?.phone||a.target_user_id||'System')+'</td><td>'+(a.amount?money(a.amount):'—')+'</td><td>'+esc(a.reason||'—')+'</td></tr>').join(''):'<tr><td colspan="5">No admin actions yet.</td></tr>'}
boot();