const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let user=null,profile=null,activeChat=null,channel=null,authMode='login',searchTimer=null,authBusy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=s=>String(s||'?').trim().slice(0,2).toUpperCase();
const authEmail=u=>`${u.trim().toLowerCase()}@login.limchat.local`;
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),3000)}
function setAuthMode(mode){if(authBusy)return;authMode=mode;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));$('#display-wrap').classList.toggle('hidden',mode!=='signup');$('#auth-submit').textContent=mode==='signup'?'Create account':'Log in'}
$$('.tab').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.auth));
function setAuthLoading(loading){const btn=$('#auth-submit');authBusy=loading;btn.disabled=loading;btn.setAttribute('aria-busy',String(loading));if(loading){btn.dataset.originalText=btn.textContent;btn.innerHTML='<span class="auth-spinner" aria-hidden="true"></span><span>Signing in…</span>'}else{btn.textContent=authMode==='signup'?'Create account':'Log in'}}
$('#auth-form').onsubmit=async e=>{e.preventDefault();if(authBusy)return;const username=$('#username').value.trim().toLowerCase(),password=$('#password').value,displayName=$('#display-name').value.trim();if(!/^[a-z0-9_]{3,24}$/.test(username)){toast('Username: 3–24 letters, numbers or underscores.');return}setAuthLoading(true);try{if(authMode==='signup'){const r=await fetch(`${SUPABASE_URL}/functions/v1/limchat-signup`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({username,password,displayName})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not create account')}const {data,error}=await db.auth.signInWithPassword({email:authEmail(username),password});if(error)throw error;if(data.session)await signedIn(data.session.user)}catch(err){toast(err.message||'Something went wrong')}finally{setAuthLoading(false)}};
async function boot(){const {data}=await db.auth.getSession();if(data.session)await signedIn(data.session.user);db.auth.onAuthStateChange(async(_e,s)=>{if(s&&!user)await signedIn(s.user);if(!s&&user)signedOut()})}
async function signedIn(u){user=u;const {data:p,error}=await db.from('limchat_profiles').select('*').eq('id',u.id).single();if(error){toast(error.message);user=null;return}profile=p;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');resetMobileHeader();setView('chats')}
function signedOut(){if(channel)db.removeChannel(channel);user=null;profile=null;activeChat=null;channel=null;$('#app').classList.add('hidden');$('#auth').classList.remove('hidden')}
$('#logout').onclick=()=>db.auth.signOut();
function setView(v){if(activeChat)closeChat(false);$$('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='chats')loadChats();if(v==='files')renderFiles();if(v==='people')renderPeople();if(v==='profile')renderProfile()}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#new-chat').onclick=()=>{setView('people');setTimeout(()=>$('#people-search')?.focus(),80)};
$('#mobile-search').onclick=()=>{setView('people');setTimeout(()=>$('#people-search')?.focus(),80)};
$('#mobile-back').onclick=e=>{e.preventDefault();e.stopPropagation();if(activeChat)closeChat(true);else setView('chats')};
$('#user-search').oninput=e=>searchPeople(e.target.value);
async function searchPeople(q){q=q.trim().toLowerCase();if(!q){$('#search-results').classList.add('hidden');return}clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{const {data,error}=await db.from('limchat_profiles').select('id,username,display_name,avatar_url').ilike('username',`${q}%`).neq('id',user.id).limit(12);if(error){toast(error.message);return}const box=$('#search-results');box.innerHTML=data?.length?data.map(personHTML).join(''):'<div class="person-row"><span class="muted">No people found.</span></div>';box.classList.remove('hidden');$$('#search-results [data-person]').forEach(x=>x.onclick=()=>startChat(x.dataset.person))},180)}
function personHTML(p){return `<button class="person-row" data-person="${p.id}"><div class="avatar">${initials(p.display_name||p.username)}</div><div><div class="chat-name">${esc(p.display_name||p.username)}</div><div class="chat-preview">@${esc(p.username)}</div></div><span class="person-arrow">›</span></button>`}
async function startChat(otherId){if(!otherId||!user)return;const {data:conversationId,error}=await db.rpc('limchat_start_direct_chat',{p_other_user:otherId});if(error){toast(error.message||'Could not start private chat');return}const {data:p,error:pe}=await db.from('limchat_profiles').select('*').eq('id',otherId).single();if(pe){toast(pe.message);return}activeChat={conversation:{id:conversationId},other:p};$('#search-results').classList.add('hidden');$('#user-search').value='';openChat()}
async function loadChats(){if(!user)return;const {data,error}=await db.rpc('limchat_get_chat_history');if(error){toast(error.message||'Could not load chats');return}const list=(data||[]).map(x=>({conversationId:x.conversation_id,p:{id:x.other_user_id,username:x.username,display_name:x.display_name,avatar_url:x.avatar_url},last:x.last_body?{body:x.last_body,created_at:x.last_created_at}:null}));renderChatList(list)}
function renderChatList(list){const desktop=$('#chat-list');const mobile=$('#view');const html=list.length?list.map(x=>`<button class="chat-row" data-chat="${x.conversationId}"><div class="avatar">${initials(x.p.display_name||x.p.username)}</div><div class="chat-info"><div class="chat-name">${esc(x.p.display_name||x.p.username)}</div><div class="chat-preview">${esc(x.last?.body||'Start the conversation')}</div></div>${x.last?.created_at?`<time class="chat-time">${new Date(x.last.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time>`:''}</button>`).join(''):`<div class="empty"><div class="empty-inner"><img class="empty-icon" src="favicon.svg" alt=""><h1>Your chats</h1><p>Search a unique username to start a private conversation. There are no invitations or friend requests.</p></div></div>`;if(desktop)desktop.innerHTML=html;if(window.matchMedia('(max-width:760px)').matches&&mobile&&!activeChat){mobile.innerHTML=`<div class="chat-list mobile-chat-list">${html}</div>`}const bind=root=>$$(`#${root} [data-chat], .${root} [data-chat]`).forEach(el=>el.onclick=()=>{const x=list.find(v=>v.conversationId===el.dataset.chat);if(x){activeChat={conversation:{id:x.conversationId},other:x.p};openChat()}});if(desktop)bind('chat-list');if(window.matchMedia('(max-width:760px)').matches)$$('.mobile-chat-list [data-chat]').forEach(el=>el.onclick=()=>{const x=list.find(v=>v.conversationId===el.dataset.chat);if(x){activeChat={conversation:{id:x.conversationId},other:x.p};openChat()}})}
async function openChat(){if(!activeChat)return;resetMobileHeader(true);const {data:msgs,error}=await db.from('limchat_messages').select('*').eq('conversation_id',activeChat.conversation.id).order('created_at');if(error){toast(error.message);return}$('#view').innerHTML=`<div class="chat-window"><header class="chat-header"><div class="avatar">${initials(activeChat.other.display_name||activeChat.other.username)}</div><div><div class="chat-user">${esc(activeChat.other.display_name||activeChat.other.username)}</div><div class="muted">@${esc(activeChat.other.username)}</div></div></header><div id="messages" class="messages">${(msgs||[]).map(messageHTML).join('')}</div><form id="composer" class="composer"><input id="message" maxlength="4000" autocomplete="off" placeholder="Message @${esc(activeChat.other.username)}"><button class="send" type="submit" aria-label="Send"><svg viewBox="0 0 24 24"><path d="m4 4 16 8-16 8 3-8z"/><path d="M7 12h13"/></svg></button></form></div>`;$('#composer').onsubmit=sendMessage;scrollMessages();subscribeMessages()}
function resetMobileHeader(inChat=false){$('.mobile-brand').classList.toggle('hidden',inChat);$('#mobile-title').classList.toggle('hidden',!inChat);$('#mobile-back').classList.toggle('hidden',!inChat);$('#mobile-search').classList.toggle('hidden',inChat);if(inChat)$('#mobile-title').textContent=activeChat?.other?.display_name||`@${activeChat?.other?.username||''}`}
function closeChat(goHome=true){if(channel){db.removeChannel(channel);channel=null}activeChat=null;resetMobileHeader(false);if(goHome)setView('chats')}
function messageHTML(m){return `<div class="bubble ${m.sender_id===user.id?'mine':''}">${esc(m.body).replace(/\n/g,'<br>')}<time>${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>`}
async function sendMessage(e){e.preventDefault();if(!activeChat)return;const input=$('#message'),body=input.value.trim();if(!body)return;input.disabled=true;const {error}=await db.from('limchat_messages').insert({conversation_id:activeChat.conversation.id,sender_id:user.id,body,message_type:'text'});if(error)toast(error.message);else{input.value='';const box=$('#messages');if(box)box.insertAdjacentHTML('beforeend',messageHTML({sender_id:user.id,body,created_at:new Date().toISOString()}));scrollMessages()}input.disabled=false;input.focus()}
function subscribeMessages(){if(channel)db.removeChannel(channel);channel=db.channel(`limchat-${activeChat.conversation.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'limchat_messages',filter:`conversation_id=eq.${activeChat.conversation.id}`},payload=>{const box=$('#messages');if(box&&payload.new.sender_id!==user.id){box.insertAdjacentHTML('beforeend',messageHTML(payload.new));scrollMessages()}}).subscribe()}
function scrollMessages(){setTimeout(()=>{const b=$('#messages');if(b)b.scrollTop=b.scrollHeight},30)}
async function renderPeople(){resetMobileHeader();$('#view').innerHTML=`<div class="page"><h1>People</h1><p class="page-sub">Find someone using their unique username.</p><div class="section-card"><div class="people-search-wrap"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input id="people-search" placeholder="Search username" autocomplete="off"></div><div id="people-results" class="person-list"></div></div></div>`;$('#people-search').oninput=e=>peopleSearch(e.target.value)}
function peopleSearch(q){q=q.trim().toLowerCase();clearTimeout(searchTimer);if(!q){$('#people-results').innerHTML='';return}searchTimer=setTimeout(async()=>{const {data,error}=await db.from('limchat_profiles').select('id,username,display_name,avatar_url').ilike('username',`${q}%`).neq('id',user.id).limit(20);if(error){toast(error.message);return}const box=$('#people-results');box.innerHTML=data?.length?data.map(personHTML).join(''):'<p class="muted">No people found.</p>';$$('#people-results [data-person]').forEach(x=>x.onclick=()=>startChat(x.dataset.person))},180)}
async function renderFiles(){resetMobileHeader();const {data:members}=await db.from('limchat_conversation_members').select('conversation_id').eq('user_id',user.id);const ids=(members||[]).map(x=>x.conversation_id);let files=[];if(ids.length){const {data}=await db.from('limchat_attachments').select('*').in('conversation_id',ids).order('created_at',{ascending:false});files=data||[]}$('#view').innerHTML=`<div class="page"><h1>Files</h1><p class="page-sub">Files shared inside your private chats.</p><div class="section-card">${files.length?files.map(f=>`<div class="file-row"><div class="file-icon"><svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/></svg></div><div class="file-name">${esc(f.file_name)}</div><span class="muted">${formatSize(f.size_bytes)}</span></div>`).join(''):'<p class="muted">No shared files yet.</p>'}</div></div>`}
function formatSize(n){if(!n)return '';if(n<1024)return `${n} B`;if(n<1048576)return `${Math.round(n/1024)} KB`;return `${(n/1048576).toFixed(1)} MB`}
function renderProfile(){resetMobileHeader();$('#view').innerHTML=`<div class="page"><h1>Profile</h1><p class="page-sub">Your Limchat identity.</p><div class="section-card"><div class="profile-head"><div class="big-avatar">${initials(profile.display_name||profile.username)}</div><div><h2 style="margin:0">${esc(profile.display_name||profile.username)}</h2><div class="muted">@${esc(profile.username)}</div></div></div></div><div class="section-card"><strong>Username</strong><p class="muted">People find you using @${esc(profile.username)}. Usernames are unique.</p><button class="danger" id="profile-logout">Log out</button></div></div>`;$('#profile-logout').onclick=()=>db.auth.signOut()}
boot();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
