const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let user=null, profile=null, activeChat=null, channel=null, authMode='login';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=s=>String(s||'?').slice(0,2).toUpperCase();
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function authEmail(u){return `${u.trim().toLowerCase()}@login.limchat.local`}
function setAuthMode(mode){authMode=mode;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.auth===mode));$('#display-wrap').classList.toggle('hidden',mode!=='signup');$('#auth-submit').textContent=mode==='signup'?'Create account':'Log in'}
$$('.tab').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.auth));
$('#auth-form').onsubmit=async e=>{e.preventDefault();const username=$('#username').value.trim().toLowerCase();const password=$('#password').value;const displayName=$('#display-name').value.trim();const btn=$('#auth-submit');btn.disabled=true;try{if(authMode==='signup'){const r=await fetch(`${SUPABASE_URL}/functions/v1/limchat-signup`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({username,password,displayName})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not create account');const {error}=await db.auth.signInWithPassword({email:authEmail(username),password});if(error)throw error;toast('Account created. Welcome to Limchat.')}else{const {error}=await db.auth.signInWithPassword({email:authEmail(username),password});if(error)throw error}}catch(err){toast(err.message||'Something went wrong')}finally{btn.disabled=false}};
async function boot(){const {data}=await db.auth.getSession();if(data.session) await signedIn(data.session.user);db.auth.onAuthStateChange((_e,s)=>{if(s&&!user)signedIn(s.user);if(!s) signedOut()})}
async function signedIn(u){user=u;const {data:p,error}=await db.from('limchat_profiles').select('*').eq('id',u.id).single();if(error){toast('Profile could not be loaded');return}profile=p;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');renderHome();await loadChats()}
function signedOut(){user=null;profile=null;activeChat=null;$('#app').classList.add('hidden');$('#auth').classList.remove('hidden');}
$('#logout').onclick=()=>db.auth.signOut();
function renderHome(){setView('chats');}
function setView(v){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='chats')loadChats();if(v==='files')renderFiles();if(v==='people')renderPeople();if(v==='profile')renderProfile()}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#mobile-search').onclick=()=>{$('#user-search').focus();$('#search-results').classList.remove('hidden');};
$('#new-chat').onclick=()=>{setView('people');setTimeout(()=>$('#people-search')?.focus(),50)};
$('#user-search').oninput=async e=>searchPeople(e.target.value); $('#user-search').onfocus=()=>$('#search-results').classList.remove('hidden');
document.addEventListener('click',e=>{if(!e.target.closest('.search')&&!e.target.closest('#search-results'))$('#search-results').classList.add('hidden')});
async function searchPeople(q){q=q.trim().toLowerCase();if(!q){$('#search-results').classList.add('hidden');return}const {data,error}=await db.from('limchat_profiles').select('id,username,display_name,avatar_url').ilike('username',`${q}%`).neq('id',user.id).limit(12);if(error)return;const box=$('#search-results');box.innerHTML=data.length?data.map(personHTML).join(''):`<div class="person-row"><div class="muted">No people found</div></div>`;box.classList.remove('hidden');box.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>startChat(x.dataset.person));}
function personHTML(p){return `<div class="person-row" data-person="${p.id}"><div class="avatar">${initials(p.display_name||p.username)}</div><div><div class="chat-name">${esc(p.display_name||p.username)}</div><div class="chat-preview">@${esc(p.username)}</div></div></div>`}
async function startChat(otherId){const {data:mine}=await db.from('limchat_conversation_members').select('conversation_id').eq('user_id',user.id);const ids=(mine||[]).map(x=>x.conversation_id);let convo=null;if(ids.length){const {data:rows}=await db.from('limchat_conversation_members').select('conversation_id').in('conversation_id',ids).eq('user_id',otherId);if(rows?.length){const {data:c}=await db.from('limchat_conversations').select('*').eq('id',rows[0].conversation_id).single();convo=c}}
if(!convo){const {data:c,error}=await db.from('limchat_conversations').insert({}).select().single();if(error){toast(error.message);return}convo=c;const {error:e}=await db.from('limchat_conversation_members').insert([{conversation_id:c.id,user_id:user.id},{conversation_id:c.id,user_id:otherId}]);if(e){toast(e.message);return}}
const {data:p}=await db.from('limchat_profiles').select('*').eq('id',otherId).single();activeChat={conversation:convo,other:p};$('#search-results').classList.add('hidden');$('#user-search').value='';openChat();}
async function loadChats(){if(!user)return;const {data:members,error}=await db.from('limchat_conversation_members').select('conversation_id').eq('user_id',user.id);if(error)return;const ids=(members||[]).map(x=>x.conversation_id);if(!ids.length){renderChatList([]);return}const {data:all}=await db.from('limchat_conversation_members').select('conversation_id,user_id').in('conversation_id',ids);const otherIds=[...new Set((all||[]).filter(x=>x.user_id!==user.id).map(x=>x.user_id))];const {data:people}=otherIds.length?await db.from('limchat_profiles').select('*').in('id',otherIds):{data:[]};const {data:msgs}=await db.from('limchat_messages').select('conversation_id,body,created_at').in('conversation_id',ids).order('created_at',{ascending:false}).limit(100);const list=ids.map(id=>{const m=all.find(x=>x.conversation_id===id&&x.user_id!==user.id);const p=people?.find(x=>x.id===m?.user_id);const last=msgs?.find(x=>x.conversation_id===id);return p?{conversationId:id,p,last}:null}).filter(Boolean);renderChatList(list)}
function renderChatList(list){const box=$('#chat-list');if(!list.length){box.innerHTML='<div class="empty" style="height:auto"><div class="empty-inner"><p>Search for a username to start your first private chat.</p></div></div>';return}box.innerHTML=list.map(x=>`<div class="chat-row" data-chat="${x.conversationId}"><div class="avatar">${initials(x.p.display_name||x.p.username)}</div><div class="chat-info"><div class="chat-name">${esc(x.p.display_name||x.p.username)}</div><div class="chat-preview">${esc(x.last?.body||'No messages yet')}</div></div></div>`).join('');box.querySelectorAll('[data-chat]').forEach(el=>el.onclick=async()=>{const id=el.dataset.chat;const item=list.find(x=>x.conversationId===id);activeChat={conversation:{id},other:item.p};openChat()})}
async function openChat(){if(!activeChat)return;$('#mobile-title').textContent=activeChat.other.display_name||`@${activeChat.other.username}`;$('.mobile-brand').classList.add('hidden');$('#mobile-title').classList.remove('hidden');$('#mobile-back').classList.remove('hidden');$('#mobile-search').classList.add('hidden');const {data:msgs,error}=await db.from('limchat_messages').select('*').eq('conversation_id',activeChat.conversation.id).order('created_at');if(error){toast(error.message);return}$('#view').innerHTML=`<div class="chat-window"><div class="chat-header"><div class="avatar">${initials(activeChat.other.display_name||activeChat.other.username)}</div><div><div class="chat-user">${esc(activeChat.other.display_name||activeChat.other.username)}</div><div class="muted">@${esc(activeChat.other.username)}</div></div></div><div id="messages" class="messages">${(msgs||[]).map(messageHTML).join('')}</div><form id="composer" class="composer"><input id="message" maxlength="4000" autocomplete="off" placeholder="Write a message…"><button class="send" type="submit">➤</button></form></div>`;scrollMessages();$('#composer').onsubmit=sendMessage;subscribeMessages()}
$('#mobile-back').onclick=()=>{if(channel){db.removeChannel(channel);channel=null}activeChat=null;$('.mobile-brand').classList.remove('hidden');$('#mobile-title').classList.add('hidden');$('#mobile-back').classList.add('hidden');$('#mobile-search').classList.remove('hidden');setView('chats')};
function messageHTML(m){return `<div class="bubble ${m.sender_id===user.id?'mine':''}">${esc(m.body).replace(/\n/g,'<br>')}<time>${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>`}
async function sendMessage(e){e.preventDefault();const input=$('#message');const body=input.value.trim();if(!body||!activeChat)return;input.disabled=true;const {error}=await db.from('limchat_messages').insert({conversation_id:activeChat.conversation.id,sender_id:user.id,body,message_type:'text'});if(error)toast(error.message);else input.value='';input.disabled=false;input.focus()}
function subscribeMessages(){if(channel)db.removeChannel(channel);channel=db.channel(`limchat:${activeChat.conversation.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'limchat_messages',filter:`conversation_id=eq.${activeChat.conversation.id}`},payload=>{const box=$('#messages');if(box&&payload.new.sender_id!==user.id)box.insertAdjacentHTML('beforeend',messageHTML(payload.new));scrollMessages()}).subscribe()}
function scrollMessages(){setTimeout(()=>{const b=$('#messages');if(b)b.scrollTop=b.scrollHeight},20)}
async function renderFiles(){const {data:members}=await db.from('limchat_conversation_members').select('conversation_id').eq('user_id',user.id);const ids=(members||[]).map(x=>x.conversation_id);let files=[];if(ids.length){const r=await db.from('limchat_attachments').select('*').in('conversation_id',ids).order('created_at',{ascending:false});files=r.data||[]}$('#view').innerHTML=`<div class="page"><h1>Files</h1><p class="muted">Files shared inside your private conversations.</p><div class="section-card">${files.length?files.map(f=>`<div class="file-row"><div class="file-icon">↗</div><div class="file-name">${esc(f.file_name)}</div><div class="muted">${formatSize(f.size_bytes)}</div></div>`).join(''):'<p class="muted">No shared files yet.</p>'}</div></div>`}
function formatSize(n){if(!n)return '';if(n<1024)return n+' B';if(n<1048576)return Math.round(n/1024)+' KB';return (n/1048576).toFixed(1)+' MB'}
async function renderPeople(){ $('#view').innerHTML=`<div class="page"><h1>People</h1><p class="muted">Find someone by their unique username.</p><div class="section-card"><input id="people-search" placeholder="Search usernames…" autocomplete="off"><div id="people-results" style="margin-top:10px"></div></div></div>`;$('#people-search').oninput=async e=>{const q=e.target.value.trim().toLowerCase();if(!q){$('#people-results').innerHTML='';return}const {data}=await db.from('limchat_profiles').select('*').ilike('username',`${q}%`).neq('id',user.id).limit(20);$('#people-results').innerHTML=(data||[]).map(personHTML).join('')||'<p class="muted">No people found.</p>';$$('#people-results [data-person]').forEach(x=>x.onclick=()=>startChat(x.dataset.person))}}
function renderProfile(){$('#view').innerHTML=`<div class="page"><h1>Profile</h1><div class="section-card"><div class="profile-head"><div class="big-avatar">${initials(profile.display_name||profile.username)}</div><div><h2 style="margin:0">${esc(profile.display_name||profile.username)}</h2><div class="muted">@${esc(profile.username)}</div></div></div></div><div class="section-card"><div class="muted">Account</div><p>Your username is unique and is how other people find you.</p><button class="danger" onclick="db.auth.signOut()">Log out</button></div></div>`}
async function renderChatNav(){await loadChats()}
boot();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
