(()=>{
  const MAX_FILE_SIZE=25*1024*1024;
  const escFile=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fileIcon=type=>type?.startsWith('image/')?'🖼️':type==='application/pdf'?'📄':'📎';
  const size=n=>n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
  const card=(a,url)=>`<div class="file-message"><div class="file-message-icon">${fileIcon(a.mime_type)}</div><div class="file-message-info"><strong>${escFile(a.file_name)}</strong><span>${size(a.size_bytes||0)}</span></div><button type="button" class="file-message-download" data-file-url="${escFile(url)}" data-file-name="${escFile(a.file_name)}" aria-label="Download file"><svg viewBox="0 0 24 24"><path d="M12 3v12M7 11l5 5 5-5M5 20h14"/></svg></button></div>`;
  function addButton(){const form=document.querySelector('#composer');if(!form||form.querySelector('#file-input'))return;const input=document.createElement('input');input.type='file';input.id='file-input';input.className='hidden';input.accept='image/*,.pdf,.txt,.zip,application/octet-stream';const b=document.createElement('button');b.type='button';b.className='file-attach';b.id='file-attach';b.title='Share a file';b.setAttribute('aria-label','Share a file');b.innerHTML='<svg viewBox="0 0 24 24"><path d="m21.4 11.6-8.8 8.8a6 6 0 0 1-8.5-8.5l9-9a4.5 4.5 0 0 1 6.4 6.4l-8.8 8.8a3 3 0 1 1-4.2-4.2l8-8"/></svg>';b.onclick=()=>input.click();input.onchange=()=>{const f=input.files?.[0];if(f)sendFile(f);input.value=''};form.insertBefore(b,form.querySelector('#message'));form.appendChild(input)}
  async function downloadFile(url,name){try{const r=await fetch(url);if(!r.ok)throw Error('Could not download file');const blob=await r.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=name||'download';a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000)}catch(e){toast(e.message||'Could not download file')}}
  document.addEventListener('click',e=>{const b=e.target.closest('.file-message-download');if(!b)return;e.preventDefault();downloadFile(b.dataset.fileUrl,b.dataset.fileName)});
  async function sendFile(file){if(!activeChat||!user)return;if(file.size>MAX_FILE_SIZE){toast('Files must be 25 MB or smaller.');return}const path=`${activeChat.conversation.id}/${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,button=document.querySelector('#file-attach');if(button)button.disabled=true;try{const up=await db.storage.from('limchat-files').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;const msg=await db.from('limchat_messages').insert({conversation_id:activeChat.conversation.id,sender_id:user.id,body:file.name,message_type:'file'}).select('id').single();if(msg.error)throw msg.error;const a=await db.from('limchat_attachments').insert({message_id:msg.data.id,conversation_id:activeChat.conversation.id,uploader_id:user.id,storage_path:path,file_name:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size}).select('*').single();if(a.error)throw a.error;const signed=await db.storage.from('limchat-files').createSignedUrl(path,3600);if(signed.error)throw signed.error;const box=document.querySelector('#messages');if(box){box.insertAdjacentHTML('beforeend',card(a.data,signed.data.signedUrl));scrollMessages()}toast('File shared')}catch(e){toast(e.message||'Could not share file')}finally{if(button)button.disabled=false}}
  const originalOpenChat=openChat;openChat=async function(){await originalOpenChat();addButton();await hydrateFiles()};
  async function hydrateFiles(){if(!activeChat)return;const {data}=await db.from('limchat_attachments').select('*').eq('conversation_id',activeChat.conversation.id).order('created_at');const box=document.querySelector('#messages');if(!box||!data?.length)return;for(const a of data){const u=await db.storage.from('limchat-files').createSignedUrl(a.storage_path,3600);if(u.data?.signedUrl)box.insertAdjacentHTML('beforeend',card(a,u.data.signedUrl))}scrollMessages()}
  const originalSubscribe=subscribeMessages;subscribeMessages=function(){if(channel)db.removeChannel(channel);channel=db.channel(`limchat-${activeChat.conversation.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'limchat_messages',filter:`conversation_id=eq.${activeChat.conversation.id}`},async payload=>{const box=document.querySelector('#messages');if(!box||payload.new.sender_id===user.id)return;if(payload.new.message_type==='file'){const {data:a}=await db.from('limchat_attachments').select('*').eq('message_id',payload.new.id).single();if(a){const u=await db.storage.from('limchat-files').createSignedUrl(a.storage_path,3600);if(u.data?.signedUrl)box.insertAdjacentHTML('beforeend',card(a,u.data.signedUrl))}}else box.insertAdjacentHTML('beforeend',messageHTML(payload.new));scrollMessages()}).subscribe()};
  new MutationObserver(addButton).observe(document.body,{childList:true,subtree:true});
})();
